#server:
#  port: 9090
#
#
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:xe
#    username: springjpa
#    password: springjpa
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#      
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace
# 

server:
  port: 9090

spring:
  output:
    ansi:
      enabled: always
      
  datasource:
    url: jdbc:oracle:thin:@oracleclouddb_high?TNS_ADMIN=/Users/jinhwankim/oraclecloud/Wallet_oracleclouddb
    username: admin
    password: Rlawlsghks4618
    driver-class-name: oracle.jdbc.OracleDriver
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
          
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
      
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  